// Generated by CoffeeScript 1.3.3
(function() {
  var audio;

  audio = new Audio;

  audio.preload = "none";

  audio.setAttribute("src", "/Moshiro_8bit/moshiro.mp3");

  audio.load();

  audio.play();

}).call(this);
