// Generated by CoffeeScript 1.3.3
(function() {
  var Moshiro, m;

  Moshiro = (function() {

    function Moshiro() {
      this.audio = new Audio;
      this.audio.preload = "none";
      this.audio.setAttribute("src", "/Moshiro_8bit/moshiro.mp3");
      this.audio.load();
      this.audio.addEventListener('ended', function() {
        return console.log("That's it!");
      });
    }

    Moshiro.prototype.play = function() {
      return this.audio.play();
    };

    return Moshiro;

  })();

  m = new Moshiro;

  window['Moshiro'] = Moshiro;

}).call(this);
