// Generated by CoffeeScript 1.3.3
(function() {
  var Moshiro;

  Moshiro = (function() {

    function Moshiro() {
      this.audio = new Audio;
      this.audio.preload = "none";
      this.audio.addEventListener('play', function() {
        return console.log("Play");
      });
      this.audio.addEventListener('loadeddata', function() {
        return console.log("Loaded data");
      });
      this.audio.addEventListener('playing', function() {
        return console.log("Playing");
      });
      this.audio.addEventListener('ended', function() {
        return console.log("Ended");
      });
      this.audio.addEventListener('timeupdate', function() {
        return document.getElementById("Tock").innerHTML = '<b>' + new Date() + '</b>';
      });
    }

    Moshiro.prototype.play = function(mp3) {
      this.audio.setAttribute("src", mp3);
      this.audio.load();
      return this.audio.play();
    };

    return Moshiro;

  })();

  window['Moshiro'] = Moshiro;

}).call(this);
